### ISSUE TITLE
generation of remaining AVC streams based on released mezzanine

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#57] opened 2022-12-07 12:52 UTC
This is to track the generation / packaging of all the remaining AVC test content based on the most recently released mezzanine.

This is currently blocked waiting on Fraunhofer and Eurofins checking the most recently generated AVC.

@rbouqueau Please correct me but I believe the following need to be generated, re-generated or packaged.
- SS1 needs to be re-generated or re-packaged as mentioned in https://github.com/cta-wave/dpctf-tests/issues/96#issuecomment-1340761182
- the long duration stream needs to be generated (for the first time) https://github.com/cta-wave/Test-Content-Generation/issues/17
- the chunking script needs to be written and run to generate the stream for the chunked tests https://github.com/cta-wave/Test-Content/issues/41
- If I look on https://cta-wave.github.io/Test-Content/ at "CFHD-SPLICING", the filenames include "2022-01-18" in them. Does this mean they need re-generating?

Does anything need doing for the encrypted streams? If I look on https://cta-wave.github.io/Test-Content/ at "CFHD-CENC", they have the same date, 2022-10-17, as the non-encrypted streams.

**Comment by rbouqueau** [comment] 2022-12-07 19:31
For SS1, I think this is good. We have an accepted content + the script is up to date. The splicing content indeed needs to be regenerated. Ok for long duration and chunked.

Encryption should be ok at this stage. It is clearkey CENC.

**Comment by rbouqueau** [comment] 2022-12-07 19:50
The name of the current mpd is suffixed with a ```_v4```. Otherwise all is final. If this were to be a problem, let's comment in [the issue](https://github.com/cta-wave/dpctf-tests/issues/96) and copy the content in a new folder (i.e. with a new date). The core of the issue is that we can't update the mpd because of the server agressive caching.

**Comment by jpiesing** [comment] 2023-04-14 08:16
@louaybassbouss @FritzHeiden over to you ....

**Comment by FritzHeiden** [comment] 2023-04-14 15:42
I regenerated the tests with the new content. They can be found here: https://github.com/cta-wave/dpctf-tests/tree/content-2023-04-06

**Comment by rbouqueau** [comment] 2023-07-12 12:55
Is this validated? Can we close this issue?

**Closed** 2023-07-18 16:18 UTC
