### ISSUE TITLE
AVC content - level too high

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/Test-Content-Generation#53] opened 2022-06-10 07:12 UTC
The _level_idc_ of encoded content is too high (42), the AVC content should be _cfhd_ - it is specified in Table 1 – WAVE Video Profiles  of CTA 5001. 
The maximum level for _cfhd_ is 40 (0x28). 

Please look to the table, to _codecs_ column. There is _avc1.640028_ not _avc1.64002A_ .

Reproducing:
```
wget https://dash.akamaized.net/WAVE/vectors/2021-09-09/avc_sets/12.5_25_50/t13/croatia_L1_1920x1080@25_60_dash_track1_init.mp4 --no-check-certificate

mp4box -diso croatia_L1_1920x1080@25_60_dash_track1_init.mp4
```
then edit xml file, and find:

`AVCLevelIndication="42"`

**Comment by rbouqueau** [comment] 2022-06-28 12:15
Thanks for the detailed report(s). Much appreciated.

I think #52 and #53 are actually the same issue.

In the code:
- The issue is that the level is hardcoded [here](https://github.com/cta-wave/Test-Content-Generation/blob/e75c7919e55b15478d6307334a08cfc6dce034dc/encode_dash.py#L160) depending on the CMAF Media Profile.
- The CMAF Media Profile is hardcoded to "avchdhf" [here](https://github.com/cta-wave/Test-Content-Generation/blob/e75c7919e55b15478d6307334a08cfc6dce034dc/run-all.py#L91).

When looking at the Annex A of CMAF (CMAF 23000-19 + Amd1 + Amd2 + Amd3 (DoC)-r10), the mapping is correct (although in the code a) how were values chosen? b) no check on max values performed).

When looking at DPCTF-s00001-v033-WAVE-DPC-v1.21, I only find references to CFHD, not to CFHF. The spec cross-references the "WAVE Content Specification" though... so I took a look at CTA-5001 and no reference to "cfhf" there.

In the helper [spreadsheet that served as a reference for the implementation](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0), the " 
AVC profile and level" and "CMAF media profile" lines were left empty.

**Comment by jpiesing** [comment] 2022-06-28 13:18
@rbouqueau I added the profile and level rows in response to this issue being reported but wasn't sure how to populate them.

**Comment by rbouqueau** [comment] 2022-07-07 05:57
@jpiesing Do you know when this will be discussed? I left 4.2 (for the reasons expressed above) in the current set.

**Comment by jpiesing** [comment] 2022-07-07 08:31
> @jpiesing Do you know when this will be discussed? I left 4.2 (for the reasons expressed above) in the current set.

It was discussed in the meeting on June 29th as follows ...

> > I think only two streams really need 4.2 - t20 (1080p50/60) and t23 (720p50/60) & that the others should fit within 4.0.
> > @All: Please can someone confirm this.
>
>  [[TS]] Yes, this is confirmed

>> @All: Should all the remaining rows be 4.0 or should some of the lower resolutions be 3.x? 
>
> [[TS]] We recommend to not go lower because 4.0 seems to be consistently supported and may cause even more questions.

> > @All: What CMAF brands are appropriate? Please can we populate the corresponding row of the above table.
> 
> [[TS]] We can populate this, but we acknowledge that level 4.2 is not supported in the content spec today. DPCTF will ask TWG and CSTF to clarify if this is intentional, in particular as 1080p/50 is a widely used format and CTA WAVE content spec would require usage of HEVC for this, no AVC profile is supported. At this stage, we go ahead as if chdf is supported and will create test content for this purpose as well.

The following table from the CMAF spec shows this ...

![image](https://user-images.githubusercontent.com/8490792/177728241-11436244-5246-455f-b5aa-e77311c844ab.png)

In contrast looking at the WAVE media spec.

![image](https://user-images.githubusercontent.com/8490792/177728555-e79011d4-73d7-4a79-bda8-210e6c009823.png)

![image](https://user-images.githubusercontent.com/8490792/177728625-0191b6fe-5a6b-4255-ab72-c6681335edff.png)

Only 'cfhd' is included in WAVE at the moment. 'chdf' needs to be added.

**Comment by rbouqueau** [comment] 2022-07-08 05:42
I will implement this unless someone objects.

**Comment by rbouqueau** [comment] 2022-09-30 00:07
This should be all good in the latest 2022-09-30 release.

**Comment by nicholas-fr** [comment] 2022-11-22 14:03
Resolved in the latest test content, see https://github.com/cta-wave/Test-Content/issues/40#issuecomment-1310031376.
I believe this issue can be closed.

**Comment by gitwjr** [comment] 2022-11-22 23:16
2022-11-22: Closed based on Nicholas' validation testing of 2022-10-17 test vectors release.

**Closed by gitwjr** 2022-11-22 23:16 UTC
