### ISSUE TITLE
avc stream t2 is supposed to be avc3 but is in fact avc1

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#47] opened 2022-06-03 12:48 UTC
AVC stream t2 is supposed to be "All AVC content options different from stream 1" specifically;

with and without picture timing SEI message: Without
with and without VUI timing information.: With
Sample entry, see CMAF clause 9.4.1.2: avc3 sample entry type (in-band parameter sets) without parameter sets within the CMAF header
CMAF Fragment durations: 5s
Initialization Constraints: Single initialization constraints, see CMAF clause 7.3.4.2 and 9.2.11.4
Fragments containing one or multiple moof/mdat pairs: Fragment contains multiple chunks (p-frame to p-frame with b-frames)
Resolution: 1920x1080
Frame rate (2.0=100/120,1.0=50/59.94/60, 0.5=25/29.97/30, 0.25=12.5/15): 0.5

It has been noted by @Lis-TV in HbbTV that if you do the following;

wget https://dash.akamaized.net/WAVE/vectors/2021-09-09/avc_sets/12.5_25_5/t2/croatia_L1_1920x1080@25_60_dash_track1_init.mp4
mp4box -diso croatia_L1_1920x1080@25_60_dash_track1_init.mp4

If you then look in croatia_L1_1920x1080@25_60_dash_track1_init_info.xml  (attached), it says avc1 ...

> &lt;AVCSampleEntryBox Size="199" Type="avc1" Specification="p15" Container="stsd"  DataReferenceIndex="1" Width="1920" Height="1080" XDPI="4718592" YDPI="4718592" BitDepth="24">

**Comment by Lis-TV** [comment] 2022-06-03 13:10
mp4box output:

`<SequenceParameterSet size="30" content="data:application/octet-string,6764002AACD940780227E5C05A808080A0000003002000000641E30632C0"/>
<PictureParameterSet size="5" content="data:application/octet-string,68EBECB22C"/>`


seems to be not in line with requirement:

`Sample entry, see CMAF clause 9.4.1.2: avc3 sample entry type (in-band parameter sets) without parameter sets within the CMAF header`

**Comment by rbouqueau** [comment] 2022-06-03 14:24
Thanks. I can reproduce on the latest version (https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t2/2022-01-17/croatia_L1_1920x1080@25_60_dash_track1_init.mp4), I'll have a look when processsing the next batch.

**Comment by Lis-TV** [comment] 2022-06-09 15:40
Seems t12 is also affected.

**Comment by rbouqueau** [comment] 2022-09-30 00:06
Should be solved by 32f04dd34d8f701edd7f4be068d5522e22a5cb9b.

**Comment by nicholas-fr** [comment] 2022-11-22 14:03
Resolved in the latest test content, see https://github.com/cta-wave/Test-Content/issues/40#issuecomment-1310031376.
I believe this issue can be closed.

**Comment by gitwjr** [comment] 2022-11-22 23:11
2022-11-22: Closed based on Nicholas' validation testing of 2022-10-17 test vectors release.

**Closed by gitwjr** 2022-11-22 23:11 UTC
